export const ASSET_NAMES = [
    "Acevedo-Kennedy",
    "Alvarez Inc",
    "Anderson Group",
    "Banks-Carlson",
    "Bender, Warren and Sanchez",
    "Campos and Sons",
    "Clarke, Lutz and Farrell",
    "Cook-Burns",
    "Davis, Allen and Rivera",
    "Duke Ltd",
    "Flynn-Anderson",
    "Foster-Flores",
    "Fox, Daniel and Coleman",
    "Good-Lewis",
    "Grant-Coffey",
    "Gray-Evans",
    "Gross PLC",
    "Guzman Ltd",
    "Hall, Meadows and Anderson",
    "Harrison, Meza and Rios",
    "Higgins, Brown and Vaughn",
    "Hooper, Evans and Merritt",
    "Horne and Sons",
    "Jimenez-Gallegos",
    "Johnson and Sons",
    "Jones Ltd",
    "Kelley, Barnes and Hutchinson",
    "Kemp-Anderson",
    "Landry, Molina and Green",
    "Marks, Garrett and Cummings",
    "Martin-Jenkins",
    "Mcknight, Beasley and Stewart",
    "Mcpherson, Simmons and Simpson",
    "Mejia, Roberts and Gay",
    "Miller-Norris",
    "Norton-Spencer",
    "Obrien-Oneill",
    "Park and Sons",
    "Patel, Norris and Jackson",
    "Patel-Brooks",
    "Perez-Robertson",
    "Pittman PLC",
    "Reid PLC",
    "Reid-Sherman",
    "Rivera Inc",
    "Roberts, Burke and Williams",
    "Robertson-Petersen",
    "Rodriguez, Roberts and Fuller",
    "Skinner-Rojas",
    "Smith-Woods",
    "Stanton-Joyce",
    "Stewart PLC",
    "Strickland-Daniels",
    "Sullivan-Curtis",
    "Taylor, Mitchell and Ward",
    "Thomas-Chavez",
    "Thompson, Davis and Brown",
    "Torres-Sanchez",
    "Vega-Huffman",
    "Wagner, Curry and Pearson",
    "Walker, Hogan and Mendez",
    "Waller Ltd",
    "Ware PLC",
    "Washington, Rogers and Morrison",
    "Watson, Evans and Smith",
    "Wiley Ltd",
    "Wilkerson-Miranda",
    "Williams Group",
    "Willis-Newman",
    "Zuniga Inc"
];

export const BUSINESS_CATEGORIES = ["Energy", "Finance", "Healthcare", "Manufacturing", "Retail", "Technology"];

export const labels = ["2030", "2040", "2050", "2060", "2070"];
